sudo: false
env:
  global:
      - secure: "GTpFf/1qzygJMurZ+xTFgZEp15t53o1Hc0FCQWSKfx7GEiq9CFMB/9VWLLYev4k8Yh7Fvepfmx7qA/U9fYDdETpBr8Itb/RWCy6SzEq2wJc1vWk/rXc7c2aQnbNY83iykiTNn2PzV7UkxWCXJcEtt+0jFwVSFUiQ3nujgdzQc5s="
      - secure: "jxy8Uhr1hThZHsnusNJNGKEjiZnuDAzCYPCJc/jpGlSyNduI0ShWp2x2KVYerigtBbo5xVIOTUP631d8Ze6k+kVUITtwFu9Ivw0w4pWCKUQ9Y1zOEridwxY57NYkEfd4AnqLwtM6l9EFfGz/LzzBLWxRy1bl8HIiYy7DjKP9sgk="
      - secure: "TUPU5tMzrmVRexqvHCXuHiugzPZsx7VyZhENzhPbpb8qSvasilOx7NaQRyC9m8Pm2NgB8Vl76rObBA5UgJ4aFt05e0vBAV6jLJvOUnBWnIAtVScT9f3aUOrYZzODRKYw6SzKgskAiptaVeVv9H36G4fGs1c1G+lLP0d+CM4aDvk="
language: android

android:
  components:
  - build-tools-21.1.2
  - android-19
  - addon-google_gdk-google-19

licenses:
  - android-sdk-license-5be876d5
  - google-gdk-license-9529f459

script:
  - ./gradlew assembleRelease

deploy:
  provider: releases
  api-key:
    secure: O8K8JFh48kkm3Sw/k4WwEyGZ2+X7+m8/GcPTh0e3NpmifwWR1tCHESo3MSMfMdM9qvxzG2OjuJDphqcIyMwM0BEySsJo3X4X8JVfH1YINFTo4thzC6FHwdMDUD7OqYPBr/5KuFcgaXb0bUFAq6WcYvwBvR0kiMW2JUKao9RzF/M=
  file: ./glass/build/outputs/apk/glass-release.apk
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
