sudo: false

language: android

android:
  components:
  - build-tools-21.1.2
  - android-19
  - addon-google_gdk-google-19

licenses:
  - android-sdk-license-5be876d5
  - google-gdk-license-9529f459

script:
  - ./gradlew assemble

deploy:
  provider: releases
  api-key:
    secure: bkWePIKomwz1uXrhg9Tqj9Ch7DS627K39eFTjNuwtn01kX7pEcxwt8wnSwlAhZP1M/NwTMxHtepc6H5cUKRAWOITuiRA6YVHYgZk6kcET2gsee4eGfWQhSz95/ANmQz1lr2EitHLp+nwAK2cmfiwA+eq3PhViYbrE9IkIx0+38o=
  file: ./glass/build/outputs/apk/glass-debug.apk
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
